routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CashoutController;
use App\Http\Controllers\CashflowController;
use App\Http\Controllers\CategoryController;
use GuzzleHttp\Middleware;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->middleware('auth');
Route::resource('/home', HomeController::class)->middleware('auth');
Route::get('/login', [AuthController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [AuthController::class, 'authenticate']);
Route::post('/logout', [AuthController::class, 'logout']);
Route::get('/register', [AuthController::class, 'register']);
Route::post('/registration', [AuthController::class, 'registration']);
Route::resource('/categories', CategoryController::class)->middleware('auth');
Route::resource('/cashflow', CashflowController::class)->middleware('auth');
Route::resource('/cashout', CashoutController::class)->middleware('auth');

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Cashflow;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Category extends Model
{
    use HasFactory;
    protected $guarded = [];

    function cashflow()
    {
        return $this->hasMany(Cashflow::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('category.index', ['title' => 'Kategori', 'category' => Category::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create', ['title' => 'Tambah Kategori']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validate = $request->validate([
            'name' => 'required'
        ]);

        try {
            Category::create($validate);
            return redirect('/categories')->with('success', 'Kategori berhasil ditambahkan!');
        } catch (Exception $e) {
            return redirect('/categories')->with('success', 'Kategori gagal ditambahkan!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('category.edit', ['title' => 'Edit Kategori', 'category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {

        $validate = $request->validate([
            'name' => 'required'
        ]);

        try {
            Category::where('id', $category->id)->update($validate);
            return redirect('/categories')->with('success', 'Kategori berhasil diupdate!');
        } catch (Exception $e) {
            return redirect('/categories')->with('success', 'Kategori gagal diupdate!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        Category::destroy($category->id);
        return redirect('/categories')->with('success-delete', 'Kategori berhasil dihapus!');
    }
}

resources/views/category/create.blade.php
@include('layouts.header')
<div class="container mt-5">
    <div class="card" style="width: 30%">
        <div class="card-header">
            Tambah Kategori
        </div>

        <div class="card-body">
            <form action="{{ route('categories.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Nama Kategori</label>
                    <input type="text" class="form-control" name="name" id="name">
                    <button type="submit" class="btn btn-primary mt-3">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>


@include('layouts.footer')

resources/views/category/edit.blade.php
@include('layouts.header')
<div class="container mt-5">
    <div class="card" style="width: 30%">
        <div class="card-header">
            Edit Kategori
        </div>

        <div class="card-body">
            <form action="{{ route('categories.update', $category->id) }}" method="post">
                @csrf
                @method('put')
                <div class="form-group">
                    <label for="name">Nama Kategori</label>
                    <input type="text" class="form-control" name="name" id="name"
                        value="{{ $category->name }}">
                    <button type="submit" class="btn btn-primary mt-3">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>


@include('layouts.footer')

resources/views/category/index.blade.php
@include('layouts.header')

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            Kategori
        </div>
        @if (session()->has('success'))
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @elseif (session()->has('success-edit'))
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ session('success-edit') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @elseif(session()->has('success-delete'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ session('success-delete') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        <div class="card-body">
            <a href="categories/create" class="btn btn-primary mb-3">Tambah Kategori</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" style="width: 10%">#</th>
                        <th scope="col" style="width: 30%">Nama Kategori</th>
                        <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($category as $c)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ $c->name }}</td>
                            <td>
                                <div class="btn-group">
                                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                        <a href="{{ route('categories.edit', $c->id) }}" type="button"
                                            class="btn btn-success btn-sm">
                                            <i class="fa-solid fa-pencil"></i> Edit
                                        </a>

                                        <form action="{{ route('categories.destroy', $c->id) }}" method="post">
                                            @csrf
                                            @method('delete')

                                            <button type="submit"
                                                onclick="return confirm('Apakah anda yakin akan menghapus data ?') "
                                                class="btn btn-danger btn-sm"><i class="fa-solid fa-trash-can"></i>
                                                Hapus</button>

                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@include('layouts.footer')