routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CashoutController;
use App\Http\Controllers\CashflowController;
use App\Http\Controllers\CategoryController;
use GuzzleHttp\Middleware;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->middleware('auth');
Route::resource('/home', HomeController::class)->middleware('auth');
Route::get('/login', [AuthController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [AuthController::class, 'authenticate']);
Route::post('/logout', [AuthController::class, 'logout']);
Route::get('/register', [AuthController::class, 'register']);
Route::post('/registration', [AuthController::class, 'registration']);
Route::resource('/categories', CategoryController::class)->middleware('auth');
Route::resource('/cashflow', CashflowController::class)->middleware('auth');
Route::resource('/cashout', CashoutController::class)->middleware('auth');

app/Models/Cashflow.php
<?php

namespace App\Models;

use App\Models\Category;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Cashflow extends Model
{
    use HasFactory;

    protected $guarded = [];

    function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/CashflowController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Models\Cashflow;
use App\Models\Category;
use Illuminate\Http\Request;

class CashflowController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('cashflow.index', ['title' => 'Daftar Transaksi', 'cashflow' => Cashflow::with('category')->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cashflow.create', ['title' => 'Transaksi', 'category' => Category::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'nominal' => 'required'
        ]);

        $validate['category_id'] = $request->category_id;
        try {
            Cashflow::create($validate);
            return redirect('/cashflow')->with('success', 'Data berhasil ditambahkan!');
        } catch (Exception $e) {
            return redirect('/cashflow')->with('success', 'Data gagal ditambahkan!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Cashflow  $cashflow
     * @return \Illuminate\Http\Response
     */
    public function show(Cashflow $cashflow)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Cashflow  $cashflow
     * @return \Illuminate\Http\Response
     */
    public function edit(Cashflow $cashflow)
    {
        return view('cashflow.edit', ['title' => 'Edit Transaksi', 'category' => Category::all(), 'cashflow' => $cashflow]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Cashflow  $cashflow
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cashflow $cashflow)
    {
        $validate = $request->validate([
            'nominal' => 'required'
        ]);

        $validate['category_id'] = $request->category_id;
        try {
            Cashflow::where('id', $cashflow->id)->update($validate);
            return redirect('/cashflow')->with('success', 'Data berhasil diupdate!');
        } catch (Exception $e) {
            return redirect('/cashflow')->with('success', 'Data gagal diupdate!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Cashflow  $cashflow
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cashflow $cashflow)
    {
        Cashflow::destroy($cashflow->id);
        return redirect('/cashflow')->with('success-delete', 'Data berhasil dihapus!');
    }
}

resources/views/cashflow/create.blade.php
@include('layouts.header')
<div class="container mt-5">
    <div class="card" style="width: 30%">
        <div class="card-header">
            Tambah Uang Masuk
        </div>

        <div class="card-body">
            <form action="{{ route('cashflow.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="category_id">Kategori</label>
                    <select class="form-control" name="category_id" id="category_id">
                        <option selected value="" disabled> &mdash; Pilih &mdash; </option>
                        @foreach ($category as $c)
                            <option value="{{ $c->id }}">{{ $c->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="nominal">Nominal</label>
                    <input type="text" class="form-control" name="nominal" id="nominal">
                    <button type="submit" class="btn btn-primary mt-3">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>


@include('layouts.footer')

resources/views/cashflow/edit.blade.php
@include('layouts.header')
<div class="container mt-5">
    <div class="card" style="width: 30%">
        <div class="card-header">
            Edit Transaksi
        </div>

        <div class="card-body">
            <form action="{{ route('cashflow.update', $cashflow->id) }}" method="post">
                @csrf
                @method('put')

                <div class="form-group">
                    <label for="category_id">Kategori</label>
                    <select class="form-control" name="category_id" id="category_id">
                        <option selected value="" disabled> &mdash; Pilih &mdash; </option>

                        @foreach ($category as $c)
                            @if ($cashflow->category_id == $c->id)
                                <option value="{{ $c->id }}" selected>{{ $c->name }}</option>
                            @else
                                <option value="{{ $c->id }}">{{ $c->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="nominal">Nominal</label>
                    <input type="text" class="form-control" name="nominal" id="nominal"
                        value="{{ $cashflow->nominal }}">
                    <button type="submit" class="btn btn-primary mt-3">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>


@include('layouts.footer')

resources/views/cashflow/index.blade.php
@include('layouts.header')

<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            Uang Masuk
        </div>
        @if (session()->has('success'))
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @elseif (session()->has('success-edit'))
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ session('success-edit') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @elseif(session()->has('success-delete'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ session('success-delete') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        <div class="card-body">
            <a href="cashflow/create" class="btn btn-primary mb-3">Tambah Transaksi</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" style="width: 10%">#</th>
                        <th scope="col" style="width: 30%">Nama Kategori</th>
                        <th scope="col" style="width: 30%">Nominal</th>
                        <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($cashflow as $c)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ $c->category->name }}</td>
                            <td>{{ 'Rp ' . number_format($c->nominal, 2, ',', '.') }}</td>
                            <td>
                                <div class="btn-group">
                                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                        <a href="{{ route('cashflow.edit', $c->id) }}" type="button"
                                            class="btn btn-success btn-sm">
                                            <i class="fa-solid fa-pencil"></i> Edit
                                        </a>

                                        <form action="{{ route('cashflow.destroy', $c->id) }}" method="post">
                                            @csrf
                                            @method('delete')

                                            <button type="submit"
                                                onclick="return confirm('Apakah anda yakin akan menghapus data ?') "
                                                class="btn btn-danger btn-sm"><i class="fa-solid fa-trash-can"></i>
                                                Hapus</button>

                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@include('layouts.footer')